--- 
author: "Divya Manian"
category_dir: categories
category_title_prefix: ""
code_dir: downloads/code
date_format: ordinal
default_asides: []
delicious_count: 3
delicious_user: ~
destination: public
disqus_short_name: nimbublog
disqus_show_comment_count: true
email: ~
excerpt_link: "Read on →"
facebook_like: false
github_repo_count: 0
github_show_profile_link: true
github_skip_forks: true
github_user: ~
githuburl: "https://github.com/nimbupani/nimbupani.github.com/blob/source/source/_posts"
google_analytics_tracking_id: UA-97188-1
google_plus_one: false
google_plus_one_size: medium
googleplus_hidden: false
googleplus_user: ~
markdown: rdiscount
paginate: 30
pagination_dir: /archives
permalink: "/:title.html"
pinboard_count: 3
pinboard_user: ~
plugins: plugins
pygments: false
recent_posts: 5
source: source
subscribe_email: ~
subscribe_rss: "http://feeds.feedburner.com/nimbupani"
subscribe_rss_webdev: "http://feeds.feedburner.com/nimbu"
subtitle: "Web Development Lemonade"
title: "Divya Manian"
twitter_follow_button: false
twitter_show_follower_count: false
twitter_show_replies: false
twitter_tweet_button: false
twitter_tweet_count: 0
twitter_user: ~
url: "http://nimbupani.github.com"

